Replace regex with password strength algorithm and add password strength bar
knjk04/book-project pull request #273
Opened 2020-08-26 19:48 UTC by tmrd993

## Summary of change
Removed the regex for the user password field and created a custom constraint to validate the password. Validation uses the password strength checking algorithm [zxcvbn4j](https://github.com/nulab/zxcvbn4j) to calculate a score between 0 and 5. Created an enum class that represents the password strength levels. Added a progress bar element to the Registration Form that represents a password strength bar. The various colors are defined in the custom-bar-styles.css file and can be changed at will.

![updatedUI](https://user-images.githubusercontent.com/47194464/91349664-e8f32f80-e7e5-11ea-825b-78ac63ecd568.png)

## Related issue

https://github.com/knjk04/book-project/issues/262

## Pull request checklist

Please ensure you have done the following:

- [x] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [x] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [x] Ensure code changes pass all tests

- [x] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request
  - [x] Included a screenshot(s) if a UI change was involved (it may look different on a reviewer's device)

- [x] Created a branch that has a descriptive name (what your branch is for a in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [x] Set this pull request to 'draft' if you are still working on it

- [x] Resolved any merge conflicts

2020-08-27 07:06 UTC, ChFlick approved these changes
Good work :+1: 

I'd suggest renaming PasswordDescriptor to PasswordStrength

2020-08-28 19:09 UTC, knjk04 requested changes
Thanks a lot for this! There's just a couple of small things to address

2020-08-28 19:09 UTC, knjk04 commented on src/main/java/com/karankumar/bookproject/backend/constraints/PasswordStrengthValidator.java
> +	return new Zxcvbn().measure(password).getScore() >= passwordStrength.getStrengthNum();
Could you ensure that the bodies of each method are indented by 4 spaces?

2020-08-28 19:10 UTC, knjk04 commented
And thanks for the review @ChFlick!

2020-08-28 19:51 UTC, tmrd993 commented
Done. I commited before merging your changes so there are two seperate commits now ( add copyright and requested changes). Sorry about that.

2020-08-29 05:33 UTC, knjk04 commented
No problem, thanks a lot!

2020-08-29 05:33 UTC, merged